import type {CountryCode} from '../data/countries';
import type {RawHoliday} from './holidayApi';
import type {ClimatePoint} from './weatherApi';
import type {SchoolHoliday} from './schoolHolidayApi';
import type {germanSchoolHolidays} from '../data/germany';
export type Preferences={year:number;deStates:string[];chCantons:string[];countries:CountryCode[];germanOn:boolean;swissOn:boolean;otherOn:boolean;weatherOn:boolean;holidaysOn:boolean;peopleWeight:number;continent:string};
export type ScoreResult={overall:number|null;crowd:number|null;weather:number|null;holiday:number|null;reasons:{kind:'positive'|'negative';text:string}[];missing:string[]};
type Inputs={germanSchoolHolidays:Record<string,{start:string;end:string;name:string}[]>;holidayData:RawHoliday[];climate:ClimatePoint|null;schoolHolidayData:SchoolHoliday[]};
const dateIn=(d:string,s:string,e:string)=>d>=s&&d<=e;
function deCount(date:string,p:Preferences,data:Inputs){if(!p.germanOn)return 0;const states=p.deStates.length?p.deStates:Object.keys(data.germanSchoolHolidays);return states.filter(st=>(data.germanSchoolHolidays[st]||[]).some(x=>dateIn(date,x.start,x.end))).length}
function holidayCount(date:string,p:Preferences,data:Inputs){if(!p.holidaysOn)return 0;const relevant=new Set<string>();if(p.germanOn)relevant.add('DE');if(p.swissOn)relevant.add('CH');if(p.otherOn)p.countries.forEach(c=>relevant.add(c));return data.holidayData.filter(h=>h.date===date&&relevant.has(h.countryCode)).length}
function schoolCount(date:string,p:Preferences,data:Inputs){let c=0;if(p.swissOn){const active=data.schoolHolidayData.filter(x=>x.region.startsWith('CH-')&&dateIn(date,x.startDate,x.endDate));const selected=p.chCantons.length?new Set(p.chCantons):null;c+=new Set(active.filter(x=>!selected||selected.has(x.region)).map(x=>x.region)).size;}if(p.otherOn){for(const country of p.countries){if(data.schoolHolidayData.some(x=>x.region.startsWith(country+'-')&&dateIn(date,x.startDate,x.endDate)))c+=1;}}return c}
function overlapProxy(date:string,p:Preferences,data:Inputs){let c=deCount(date,p,data)+schoolCount(date,p,data);if(p.swissOn)c+=data.holidayData.filter(h=>h.date===date&&h.countryCode==='CH').length;if(p.otherOn)c+=data.holidayData.filter(h=>h.date===date&&p.countries.includes(h.countryCode as CountryCode)).length;return c}
function weatherScore(date:string,climate:ClimatePoint|null):number|null{if(!climate)return null;const month=Number(date.slice(5,7));const seasonal=Math.sin(((month-1)/12)*Math.PI*2-Math.PI/2);const tempSuit=100-Math.min(100,Math.abs(climate.temperature-20)*5);const precipPenalty=Math.min(50,climate.precipitation/4);const sunshineBonus=Math.min(30,climate.sunshine*2);const seasonAdj=seasonal*8;return Math.max(0,Math.min(100,tempSuit-precipPenalty+sunshineBonus+seasonAdj));}
export function calculateTravelScore(date:string,p:Preferences,data:Inputs):ScoreResult{const reasons:{kind:'positive'|'negative';text:string}[]=[];const missing:string[]=[];const de=deCount(date,p,data);const school=schoolCount(date,p,data);const holidays=holidayCount(date,p,data);const overlap=overlapProxy(date,p,data);let crowd:number|null=null; if(p.germanOn||p.swissOn||p.otherOn){crowd=Math.max(0,Math.min(100,overlap*11 + (new Date(date+'T12:00:00Z').getUTCDay()===0||new Date(date+'T12:00:00Z').getUTCDay()===6?10:0)));if(de===0&&school===0)reasons.push({kind:'positive',text:'Keine ausgewählten Schulferien'});else if(de>0||school>0) reasons.push({kind:'negative',text:`Schulferien in ${de} ausgewählten deutschen Regionen`});if(overlap<=1)reasons.push({kind:'positive',text:'Geringe Ferien-/Feiertagsüberschneidung'});if(overlap>=4)reasons.push({kind:'negative',text:'Mehrere relevante Ferien-/Feiertagsfaktoren überschneiden sich'});}
 let holiday:number|null=null;if(p.holidaysOn){holiday=Math.max(0,100-holidays*18);if(holidays===0)reasons.push({kind:'positive',text:'Keine ausgewählten Feiertage am Tag'});else reasons.push({kind:'negative',text:`${holidays} ausgewählte Feiertagsfaktoren`});}
 let weather:number|null=null;if(p.weatherOn){weather=weatherScore(date,data.climate);if(weather==null)missing.push(`Wetter (${p.continent})`);else if(weather>=70)reasons.push({kind:'positive',text:'Günstiger Klimaindikator für den gewählten Referenzpunkt'});else reasons.push({kind:'negative',text:'Klimaindikator ist außerhalb des bevorzugten Bereichs'});}
 if(p.holidaysOn&&holiday!==null&&holiday>=90)reasons.push({kind:'positive',text:'Keine relevanten Feiertagsbelastungen'});
 if(p.weatherOn&&p.germanOn===false&&p.swissOn===false&&p.otherOn===false)missing.push('Auslastungsfaktoren');
 const crowdGood=crowd==null?null:100-crowd; const components:number[]=[];const weights:number[]=[];if(crowdGood!=null){components.push(crowdGood);weights.push(p.peopleWeight)}if(weather!=null){components.push(weather);weights.push(100-p.peopleWeight)}if(holiday!=null){components.push(holiday);weights.push(10)}if(!components.length)return {overall:null,crowd,weather,holiday,reasons,missing};const overall=components.reduce((sum,v,i)=>sum+v*weights[i],0)/weights.reduce((a,b)=>a+b,0);return {overall,crowd,weather,holiday,reasons,missing};}
